name: trunk

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.trunk
  cancel-in-progress: true

jobs:
  execute:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      id-token: write

    steps:
      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check source code change
        id: src-change
        uses: ./.github/actions/check-changes
        with:
          pattern: "src/*.sh"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          check-latest: true

      - name: Variables
        id: variables
        run: |
          PACKAGE_VERSION=$(jq --raw-output ".version" <./package.json)
          PUBLISHED_PACKAGE_VERSION=$(curl -s "${PACKAGE_URL}" | jq --raw-output ".version")
          SHOULD_PUBLISH='false'
          if [ "${PACKAGE_VERSION}" != "${PUBLISHED_PACKAGE_VERSION}" ]; then SHOULD_PUBLISH='true'; fi
          echo "publish=$(echo ${SHOULD_PUBLISH})" >> $GITHUB_OUTPUT
        env:
          PACKAGE_URL: "https://registry.npmjs.com/material-design-icon-fonts-self-hosted-web/latest"

      - name: Lint shell
        if: steps.src-change.outputs.change == 'true'
        run: |
          sudo apt install -y shellcheck
          yarn lint

      - name: Generate
        if: steps.variables.outputs.publish == 'true'
        run: yarn install

      - name: NPM Publish
        if: steps.variables.outputs.publish == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.head_ref }}
          EVENT_TYPE: npm_publish
        run: |
          gh api \
            -X POST \
            /repos/${REPO}/dispatches \
            --header 'Accept: application/vnd.github+json' \
            --input - <<EOF
          {
            "event_type": "${EVENT_TYPE}",
            "client_payload": {
              "ref": "${BRANCH}"
            }
          }
          EOF
