name: validate-pr

on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}.${{ github.sha }}.validate-pr
  cancel-in-progress: true

jobs:
  premerge:
    runs-on: ubuntu-latest

    steps:
      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch origin for checks
        run: |
          git checkout -b premerge
          git fetch origin main:main

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          check-latest: true

      - name: Lint shell
        run: |
          sudo apt update
          sudo apt install -y shellcheck
          yarn lint

      - name: Variables
        id: variables
        run: |
          PACKAGE_VERSION=$(jq --raw-output ".version" <./package.json)
          PUBLISHED_PACKAGE_VERSION=$(curl -s "${PACKAGE_URL}" | jq --raw-output ".version")
          SHOULD_PUBLISH='false'
          if [ "${PACKAGE_VERSION}" != "${PUBLISHED_PACKAGE_VERSION}" ]; then SHOULD_PUBLISH='true'; fi
          echo "publish=$(echo ${SHOULD_PUBLISH})" >> $GITHUB_OUTPUT
        env:
          PACKAGE_URL: "https://registry.npmjs.com/material-design-icon-fonts-self-hosted-web/latest"

      - name: Generate
        if: steps.variables.outputs.publish == 'true'
        run: yarn install

      - name: NPM publish
        if: steps.variables.outputs.publish == 'true'
        uses: ./.github/actions/npm-publish
        with:
          use-trusted-publishing: true
          dry-run: true
